# Generated by Django 3.1.2 on 2020-12-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20201219_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audio_file',
            field=models.FileField(default=False, upload_to='audio_files'),
        ),
    ]
