# Generated by Django 3.1.2 on 2020-11-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20201119_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='secondary_category',
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_category',
            field=models.ManyToManyField(blank=True, to='cart.Category'),
        ),
    ]
